---
version: 1
formatters:
  simple:
    format: '%(levelname)s - %(message)s'
  precise:
    format: '%(asctime)s - %(levelname)s - %(message)s'

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout
  importLogHandler:
    class : logging.FileHandler
    level: ERROR
    formatter: simple
    mode: w
    filename: logs/import_errors.log
  importLogDebugHandler:
    class : logging.FileHandler
    level: DEBUG
    formatter: simple
    mode: w
    filename: logs/import_errors.log  
  exportLogDebugHandler:
    class : logging.FileHandler
    level: DEBUG
    formatter: simple
    mode: w
    filename: logs/export_errors.log  

loggers:
  import_log:
    level: DEBUG
    handlers: [importLogDebugHandler]
    propagate: 1
  export_log:
    level: DEBUG
    handlers: [exportLogDebugHandler]
    propagate: 1
  console:
    level: DEBUG
    handlers: [console]
    propagate: no    
root:
  level: DEBUG
  handlers: [console]